### ISSUE TITLE
problem with include header in a .h module

### ISSUE THREAD

**Issue by alirezainallo** [mikalhart/TinyGPSPlus#117]
hi
i want to use a driver on this library. I'm using esp32 on platformIO.
but when i call <code>#include <TinyGPSPlus.h></code>:
![image](https://user-images.githubusercontent.com/96906718/224311327-4ff2bd80-883d-48d0-8590-6e0fe967e23d.png)
give me many error:
![image](https://user-images.githubusercontent.com/96906718/224311607-b563ac7a-8536-4ca0-9d43-5342b3f4ae1d.png)

but when call <code>#include <TinyGPSPlus.h></code> directly in my main.cpp every things are Ok and doesn't return these error.
can you tell me why?🙏

**Comment by mikalhart** [comment]
@alirezainallo I'm guessing that because the file you are compiling (neo6GPS.c) is C, that your build is using the C compiler instead of the C++ compiler.  TinyGPS++ requires C++ for concepts like 'public', 'friend', and 'class'.  Maybe the solution is as simple as renaming neo6GPS.c to neo6GPS.cpp?

**Comment by alirezainallo** [comment]
> @alirezainallo I'm guessing that because the file you are compiling (neo6GPS.c) is C, that your build is using the C compiler instead of the C++ compiler.  TinyGPS++ requires C++ for concepts like 'public', 'friend', and 'class'.  Maybe the solution is as simple as renaming neo6GPS.c to neo6GPS.cpp?

Thanks my problem solved🙏🏻
Was exactly that neo6GPS file extention
I change it to .cpp and solved.
